/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthVerifyRequestRouteImport } from './routes/_auth/verify-request'
import { Route as AuthErrorRouteImport } from './routes/_auth/error'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAccountSettingsRouteImport } from './routes/_protected/account/settings'
import { Route as ProtectedAccountMetricsLayoutRouteImport } from './routes/_protected/account/_metricsLayout'
import { Route as ProtectedAccountMetricsLayoutIndexRouteImport } from './routes/_protected/account/_metricsLayout/index'
import { Route as ProtectedAccountMetricsLayoutProductsRouteImport } from './routes/_protected/account/_metricsLayout/products'
import { Route as ProtectedAccountMetricsLayoutProductSlugRouteImport } from './routes/_protected/account/_metricsLayout/product.$slug'

const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthVerifyRequestRoute = AuthVerifyRequestRouteImport.update({
  id: '/verify-request',
  path: '/verify-request',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountSettingsRoute =
  ProtectedAccountSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedAccountMetricsLayoutRoute =
  ProtectedAccountMetricsLayoutRouteImport.update({
    id: '/_metricsLayout',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedAccountMetricsLayoutIndexRoute =
  ProtectedAccountMetricsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAccountMetricsLayoutRoute,
  } as any)
const ProtectedAccountMetricsLayoutProductsRoute =
  ProtectedAccountMetricsLayoutProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ProtectedAccountMetricsLayoutRoute,
  } as any)
const ProtectedAccountMetricsLayoutProductSlugRoute =
  ProtectedAccountMetricsLayoutProductSlugRouteImport.update({
    id: '/product/$slug',
    path: '/product/$slug',
    getParentRoute: () => ProtectedAccountMetricsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/auth': typeof AuthAuthRoute
  '/error': typeof AuthErrorRoute
  '/verify-request': typeof AuthVerifyRequestRoute
  '/account': typeof ProtectedAccountMetricsLayoutRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/account/settings': typeof ProtectedAccountSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/products': typeof ProtectedAccountMetricsLayoutProductsRoute
  '/account/': typeof ProtectedAccountMetricsLayoutIndexRoute
  '/account/product/$slug': typeof ProtectedAccountMetricsLayoutProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/auth': typeof AuthAuthRoute
  '/error': typeof AuthErrorRoute
  '/verify-request': typeof AuthVerifyRequestRoute
  '/account': typeof ProtectedAccountMetricsLayoutIndexRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/account/settings': typeof ProtectedAccountSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/products': typeof ProtectedAccountMetricsLayoutProductsRoute
  '/account/product/$slug': typeof ProtectedAccountMetricsLayoutProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/error': typeof AuthErrorRoute
  '/_auth/verify-request': typeof AuthVerifyRequestRoute
  '/_protected/account': typeof ProtectedAccountRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/account/_metricsLayout': typeof ProtectedAccountMetricsLayoutRouteWithChildren
  '/_protected/account/settings': typeof ProtectedAccountSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/account/_metricsLayout/products': typeof ProtectedAccountMetricsLayoutProductsRoute
  '/_protected/account/_metricsLayout/': typeof ProtectedAccountMetricsLayoutIndexRoute
  '/_protected/account/_metricsLayout/product/$slug': typeof ProtectedAccountMetricsLayoutProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/auth'
    | '/error'
    | '/verify-request'
    | '/account'
    | '/onboarding'
    | '/account/settings'
    | '/api/auth/$'
    | '/account/products'
    | '/account/'
    | '/account/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/auth'
    | '/error'
    | '/verify-request'
    | '/account'
    | '/onboarding'
    | '/account/settings'
    | '/api/auth/$'
    | '/account/products'
    | '/account/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/deferred'
    | '/_auth/auth'
    | '/_auth/error'
    | '/_auth/verify-request'
    | '/_protected/account'
    | '/_protected/onboarding'
    | '/_protected/account/_metricsLayout'
    | '/_protected/account/settings'
    | '/api/auth/$'
    | '/_protected/account/_metricsLayout/products'
    | '/_protected/account/_metricsLayout/'
    | '/_protected/account/_metricsLayout/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/verify-request': {
      id: '/_auth/verify-request'
      path: '/verify-request'
      fullPath: '/verify-request'
      preLoaderRoute: typeof AuthVerifyRequestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/error': {
      id: '/_auth/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/settings': {
      id: '/_protected/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof ProtectedAccountSettingsRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/account/_metricsLayout': {
      id: '/_protected/account/_metricsLayout'
      path: ''
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountMetricsLayoutRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/account/_metricsLayout/': {
      id: '/_protected/account/_metricsLayout/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAccountMetricsLayoutIndexRouteImport
      parentRoute: typeof ProtectedAccountMetricsLayoutRoute
    }
    '/_protected/account/_metricsLayout/products': {
      id: '/_protected/account/_metricsLayout/products'
      path: '/products'
      fullPath: '/account/products'
      preLoaderRoute: typeof ProtectedAccountMetricsLayoutProductsRouteImport
      parentRoute: typeof ProtectedAccountMetricsLayoutRoute
    }
    '/_protected/account/_metricsLayout/product/$slug': {
      id: '/_protected/account/_metricsLayout/product/$slug'
      path: '/product/$slug'
      fullPath: '/account/product/$slug'
      preLoaderRoute: typeof ProtectedAccountMetricsLayoutProductSlugRouteImport
      parentRoute: typeof ProtectedAccountMetricsLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthVerifyRequestRoute: typeof AuthVerifyRequestRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthVerifyRequestRoute: AuthVerifyRequestRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAccountMetricsLayoutRouteChildren {
  ProtectedAccountMetricsLayoutProductsRoute: typeof ProtectedAccountMetricsLayoutProductsRoute
  ProtectedAccountMetricsLayoutIndexRoute: typeof ProtectedAccountMetricsLayoutIndexRoute
  ProtectedAccountMetricsLayoutProductSlugRoute: typeof ProtectedAccountMetricsLayoutProductSlugRoute
}

const ProtectedAccountMetricsLayoutRouteChildren: ProtectedAccountMetricsLayoutRouteChildren =
  {
    ProtectedAccountMetricsLayoutProductsRoute:
      ProtectedAccountMetricsLayoutProductsRoute,
    ProtectedAccountMetricsLayoutIndexRoute:
      ProtectedAccountMetricsLayoutIndexRoute,
    ProtectedAccountMetricsLayoutProductSlugRoute:
      ProtectedAccountMetricsLayoutProductSlugRoute,
  }

const ProtectedAccountMetricsLayoutRouteWithChildren =
  ProtectedAccountMetricsLayoutRoute._addFileChildren(
    ProtectedAccountMetricsLayoutRouteChildren,
  )

interface ProtectedAccountRouteChildren {
  ProtectedAccountMetricsLayoutRoute: typeof ProtectedAccountMetricsLayoutRouteWithChildren
  ProtectedAccountSettingsRoute: typeof ProtectedAccountSettingsRoute
}

const ProtectedAccountRouteChildren: ProtectedAccountRouteChildren = {
  ProtectedAccountMetricsLayoutRoute:
    ProtectedAccountMetricsLayoutRouteWithChildren,
  ProtectedAccountSettingsRoute: ProtectedAccountSettingsRoute,
}

const ProtectedAccountRouteWithChildren =
  ProtectedAccountRoute._addFileChildren(ProtectedAccountRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  DeferredRoute: DeferredRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
