/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthErrorRouteImport } from './routes/_auth/error'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAccountSettingsRouteImport } from './routes/_protected/account/settings'
import { Route as ProtectedAccountProductsRouteImport } from './routes/_protected/account/products'
import { Route as ProtectedAccountProductSlugRouteImport } from './routes/_protected/account/product.$slug'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAccountRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountSettingsRoute =
  ProtectedAccountSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedAccountProductsRoute =
  ProtectedAccountProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedAccountProductSlugRoute =
  ProtectedAccountProductSlugRouteImport.update({
    id: '/product/$slug',
    path: '/product/$slug',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/docs': typeof DocsRoute
  '/auth': typeof AuthAuthRoute
  '/error': typeof AuthErrorRoute
  '/account': typeof ProtectedAccountRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/account/products': typeof ProtectedAccountProductsRoute
  '/account/settings': typeof ProtectedAccountSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/': typeof ProtectedAccountIndexRoute
  '/account/product/$slug': typeof ProtectedAccountProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/docs': typeof DocsRoute
  '/auth': typeof AuthAuthRoute
  '/error': typeof AuthErrorRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/account/products': typeof ProtectedAccountProductsRoute
  '/account/settings': typeof ProtectedAccountSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/account/product/$slug': typeof ProtectedAccountProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/docs': typeof DocsRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/error': typeof AuthErrorRoute
  '/_protected/account': typeof ProtectedAccountRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/account/products': typeof ProtectedAccountProductsRoute
  '/_protected/account/settings': typeof ProtectedAccountSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
  '/_protected/account/product/$slug': typeof ProtectedAccountProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/docs'
    | '/auth'
    | '/error'
    | '/account'
    | '/onboarding'
    | '/account/products'
    | '/account/settings'
    | '/api/auth/$'
    | '/account/'
    | '/account/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/docs'
    | '/auth'
    | '/error'
    | '/onboarding'
    | '/account/products'
    | '/account/settings'
    | '/api/auth/$'
    | '/account'
    | '/account/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/deferred'
    | '/docs'
    | '/_auth/auth'
    | '/_auth/error'
    | '/_protected/account'
    | '/_protected/onboarding'
    | '/_protected/account/products'
    | '/_protected/account/settings'
    | '/api/auth/$'
    | '/_protected/account/'
    | '/_protected/account/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  DocsRoute: typeof DocsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/error': {
      id: '/_auth/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/settings': {
      id: '/_protected/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof ProtectedAccountSettingsRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/account/products': {
      id: '/_protected/account/products'
      path: '/products'
      fullPath: '/account/products'
      preLoaderRoute: typeof ProtectedAccountProductsRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/account/product/$slug': {
      id: '/_protected/account/product/$slug'
      path: '/product/$slug'
      fullPath: '/account/product/$slug'
      preLoaderRoute: typeof ProtectedAccountProductSlugRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthErrorRoute: typeof AuthErrorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthErrorRoute: AuthErrorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAccountRouteChildren {
  ProtectedAccountProductsRoute: typeof ProtectedAccountProductsRoute
  ProtectedAccountSettingsRoute: typeof ProtectedAccountSettingsRoute
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
  ProtectedAccountProductSlugRoute: typeof ProtectedAccountProductSlugRoute
}

const ProtectedAccountRouteChildren: ProtectedAccountRouteChildren = {
  ProtectedAccountProductsRoute: ProtectedAccountProductsRoute,
  ProtectedAccountSettingsRoute: ProtectedAccountSettingsRoute,
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
  ProtectedAccountProductSlugRoute: ProtectedAccountProductSlugRoute,
}

const ProtectedAccountRouteWithChildren =
  ProtectedAccountRoute._addFileChildren(ProtectedAccountRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  DeferredRoute: DeferredRoute,
  DocsRoute: DocsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
